#!/usr/bin/env node
/**
 * deploy-web.js — One-shot build + commit + push for the web dashboard.
 *
 * Pipeline:
 *   1. node scripts/build-web.js
 *      → Builds Next.js with /app basePath, copies ./out into
 *        ../../website/public/app/.
 *   2. cd ../../website && git add public/app
 *   3. git diff --staged --quiet      → exit 0 if no changes (skip)
 *   4. git commit -m "Rebuild dashboard (<short hash of bundle>)"
 *   5. git push
 *
 * Refuses to push if the working tree has unrelated staged changes,
 * to avoid accidentally bundling unrelated edits into the deploy.
 */
'use strict';

const { spawnSync, execSync } = require('child_process');
const fs   = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT_FRONTEND = path.resolve(__dirname, '..');
const WEBSITE_REPO  = path.resolve(ROOT_FRONTEND, '..', '..', 'website');
const TARGET_DIR    = path.join(WEBSITE_REPO, 'public', 'app');

function run(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, { stdio: 'inherit', ...opts });
  if (r.status !== 0) {
    console.error(`✗ Command failed: ${cmd} ${args.join(' ')}`);
    process.exit(r.status ?? 1);
  }
  return r;
}

function runCapture(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, { encoding: 'utf8', ...opts });
  return { status: r.status ?? 0, stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim() };
}

// ── Step 1: build ──────────────────────────────────────────────────────────
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log(' Step 1/4  Build');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
run(process.execPath, [path.join(__dirname, 'build-web.js')]);

if (!fs.existsSync(WEBSITE_REPO) || !fs.existsSync(path.join(WEBSITE_REPO, '.git'))) {
  console.error('✗ Website git repo not found at', WEBSITE_REPO);
  process.exit(1);
}

// ── Step 2: check working tree state ────────────────────────────────────────
console.log('');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log(' Step 2/4  Check website repo');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
const status = runCapture('git', ['status', '--porcelain'], { cwd: WEBSITE_REPO });
const lines = status.stdout.split('\n').filter(Boolean);
const dashboardChanges = lines.filter(l => l.includes('public/app'));
const unrelated        = lines.filter(l => !l.includes('public/app'));

if (unrelated.length > 0) {
  console.error('✗ Refusing to deploy — there are unrelated changes in the website repo:');
  for (const l of unrelated) console.error('   ' + l);
  console.error('   Commit, stash, or revert these first, then re-run npm run deploy:web.');
  process.exit(1);
}
if (dashboardChanges.length === 0) {
  console.log('• No dashboard changes detected — nothing to deploy.');
  process.exit(0);
}
console.log(`• ${dashboardChanges.length} dashboard files changed.`);

// ── Step 3: stage + commit ──────────────────────────────────────────────────
console.log('');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log(' Step 3/4  Commit');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
run('git', ['add', 'public/app'], { cwd: WEBSITE_REPO });

// Build a stable short hash of the new bundle so the commit message is unique
let bundleHash = 'unknown';
try {
  const indexHtml = fs.readFileSync(path.join(TARGET_DIR, 'index.html'));
  bundleHash = crypto.createHash('sha1').update(indexHtml).digest('hex').slice(0, 8);
} catch { /* ignore — fall back to "unknown" */ }

const commitMsg = `Rebuild web dashboard (${bundleHash})\n\nAuto-generated by npm run deploy:web.`;
run('git', ['commit', '-m', commitMsg], { cwd: WEBSITE_REPO });

// ── Step 4: push ────────────────────────────────────────────────────────────
console.log('');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log(' Step 4/4  Push');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
run('git', ['push', 'origin', 'HEAD'], { cwd: WEBSITE_REPO });

console.log('');
console.log('✓ Deployed. Runway should redeploy in ~60 seconds.');
console.log('  Test at https://watchdogbot.cloud/app/');
